### ISSUE TITLE
Instal docker cli instead of daemon inside container

### ISSUE THREAD

**Issue by glazeus** [lifeci/onbuild#1]
Reason: Reduce size and eliminate unwanted dependencies

```Dockerfile
ENV DOCKERVERSION=18.03.1-ce
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
  && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 \
                 -C /usr/local/bin docker/docker \
  && rm docker-${DOCKERVERSION}.tgz

RUN adduser docker --no-create-home --uid 1001 --system; \
        chown docker /var/run/docker.sock
USER docker
```

source: https://stackoverflow.com/questions/38675925/is-it-possible-to-install-only-the-docker-cli-and-not-the-daemon

**Comment by rjudin** [comment]
added possibility to install cli instead of full runtime: https://github.com/lifeci/onbuild/commit/b57ccc50d6d9b5a9209e181405369ae204f9ee82
